spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# UTR API Configuration
# For production environments, it's recommended to set this via the UTR_API_TOKEN environment variable instead
# This property will be used as a fallback if the environment variable is not set
utr.api.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNZW1iZXJJZCI6Ijc5MjQxNyIsImVtYWlsIjoibWxpZW1AdXdhdGVybG9vLmNhIiwiVmVyc2lvbiI6IjEiLCJEZXZpY2VMb2dpbklkIjoiMjA1MzUxOTQiLCJuYmYiOjE3MjI1NzYyNzEsImV4cCI6MTcyNTE2ODI3MSwiaWF0IjoxNzIyNTc2MjcxfQ.Rswtpx-FhntQok9Fuo0E60l2nXjlgvpdbA87Vnw_6gw

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://db-mysql-match-do-user-16025444-0.c.db.ondigitalocean.com:25060/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=doadmin
spring.datasource.password=your_password

spring.datasource.tomcat.initial-size=15
spring.datasource.tomcat.max-wait=20000
spring.datasource.tomcat.max-active=50
spring.datasource.tomcat.max-idle=15
spring.datasource.tomcat.min-idle=8
spring.datasource.tomcat.default-auto-commit=true
#spring.jpa.show-sql=true

logging.level.org.hibernate=error
logging.level.com.utr=debug
logging.level.com.utr.match=debug
logging.level.com.utr.match.batch=debug

#google sheets config
application.name=MatchApp
spreadsheet.id=1Iti9NNTefNFF9u-j6KW-SazgurdBFTke3fj1r4c-mCE
credentials.file.path=/credentials.json
tokens.directory.path=tokens
