apiVersion: apps.tess.io/v1alpha3
kind: FederatedDeployment
metadata:
  name: match-node-app
  namespace: hellotessapp-staging
spec:
  applicationInstanceRef:
    kind: ApplicationInstance
    name: hellotessapp-staging-ai
    namespace: hellotessapp-staging
  deployments:
    - name: fcp
      type: Global
      strategy:
        base:
          replicas: 2
          template:
            spec:
              selector:
                matchLabels:
                  applicationinstance.tess.io/name: hellotessapp-staging-ai
              strategy:
                rollingUpdate:
                  maxSurge: 25%
                  maxUnavailable: 25%
                type: RollingUpdate
              template:
                metadata:
                  labels:
                    applicationinstance.tess.io/name: hellotessapp-staging-ai
                spec:
                  containers:
                    - image: hub.tess.io/yanzxu/match-node-app:v2
                      imagePullPolicy: Always
                      name: match-app
                  ports:
                    - containerPort: 3000
        placement:
          clusters:
            - "130"
        rollout:
          rollingUpdate:
            maxUnavailable: 1
          type: RollingUpdate
        supervisor:
          tiers:
            - Global
            - Cluster
          type: Global